apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"patch-k8s-server"},"name":"patch-k8s-server","namespace":"datatunerx-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"patch-k8s-server"}},"template":{"metadata":{"labels":{"app":"patch-k8s-server"}},"spec":{"containers":[{"env":[{"name":"KUBECONFIG","value":"/root/.kube/config"}],"image":"10.33.1.11:9090/datatunerx/datatunerx-server:20231215","name":"patch-k8s-server","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"2","memory":"2Gi"},"requests":{"cpu":"1","memory":"1Gi"}},"volumeMounts":[{"mountPath":"/root/.kube/config","name":"kube-config"}]}],"volumes":[{"hostPath":{"path":"/root/.kube/config"},"name":"kube-config"}]}}}}
  creationTimestamp: "2023-12-15T07:28:02Z"
  generation: 1
  labels:
    app: patch-k8s-server
  name: patch-k8s-server
  namespace: datatunerx-dev
  resourceVersion: "5879904"
  uid: a059738f-f9f5-4b55-a760-3103da5d04be
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: patch-k8s-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: patch-k8s-server
    spec:
      containers:
      - env:
        - name: KUBECONFIG
          value: /root/.kube/config
        - name: PROMETHEUS_API_URL
          value: http://10.33.1.10:30722
        image: 10.33.1.11:9090/datatunerx/datatunerx-server:20231215
        imagePullPolicy: IfNotPresent
        name: patch-k8s-server
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.kube/config
          name: kube-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /root/.kube/config
          type: ""
        name: kube-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-12-15T07:28:06Z"
    lastUpdateTime: "2023-12-15T07:28:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-12-15T07:28:02Z"
    lastUpdateTime: "2023-12-15T07:28:06Z"
    message: ReplicaSet "patch-k8s-server-57fbf584b8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
