apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "datatunerx.fullname" . }}
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ["get", "watch", "list", "create", "patch", "update", "delete"]
  - nonResourceURLs: ['*']
    verbs: ["get"]
