kind: Deployment
apiVersion: apps/v1
metadata:
  name: datatunerx-ui
  namespace: datatunerx
  labels:
    app: datatunerx-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datatunerx-ui
  template:
    metadata:
      name: datatunerx-ui
      labels:
        app: datatunerx-ui
    spec:
      containers:
        - name: datatunerx-ui
          image: release.daocloud.io/max/datatunerx-ui:v0.0.2
          imagePullPolicy: Always
          ports:
          - containerPort: 8443
          resources:
            limits:
              cpu: 500m
              memory: 0.5Gi
            requests:
              cpu: 500m
              memory: 0.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: datatunerx-ui
  namespace: datatunerx
spec:
  type: NodePort
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: datatunerx-ui
