kind: Deployment
apiVersion: apps/v1
metadata:
  name: datatunerx-ui
  namespace: datatunerx
  labels:
    app: datatunerx-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datatunerx-ui
  template:
    metadata:
      name: datatunerx-ui
      labels:
        app: datatunerx-ui
    spec:
      containers:
        - name: datatunerx-ui
          image: release.daocloud.io/datatunerx/datatunerx-console:v0.0.1-dev-1765f8b
          env:
          - name: 'API_URL'
            value: "https://10.29.26.43:6443"
          imagePullPolicy: Always
          ports:
          - containerPort: 8443
          resources:
            limits:
              cpu: 500m
              memory: 0.5Gi
            requests:
              cpu: 500m
              memory: 0.5Gi
      serviceAccountName: ns-admin
