apiVersion: v1
kind: Service
metadata:
  name: datatunerx-ui
  namespace: datatunerx-dev
spec:
  type: NodePort
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: datatunerx-ui
