apiVersion: ray.io/v1
kind: RayService
metadata:
  name: finetune-sampleasdf
  namespace: datatunerx-dev
  labels:
    createdByFrontend: "true"
spec:
  rayClusterConfig:
    headGroupSpec:
      rayStartParams:
        dashboard-host: 0.0.0.0
        num-gpus: "0"
      serviceType: NodePort
      template:
        spec:
          containers:
            - name: ray-head
              image: 10.33.1.11:9090/datatunerx/ray271-llama2-7b-finetune-checkpoint-liantiao-test-vepk:20231213
              ports:
                - containerPort: 6379
                  name: gcs-server
                  protocol: TCP
                - containerPort: 8265
                  name: dashboard
                  protocol: TCP
                - containerPort: 10001
                  name: client
                  protocol: TCP
                - containerPort: 8000
                  name: serve
                  protocol: TCP
              resources:
                limits:
                  cpu: 2000m
                  memory: 8Gi
                requests:
                  cpu: 1000m
                  memory: 4Gi
          nodeSelector:
            kubernetes.io/hostname: 10-33-1-11
          tolerations:
          - effect: NoSchedule
            key: nvidia.com/gpu
            operator: Exists
          - effect: NoSchedule
            key: node.kubernetes.io/disk-pressure
            operator: Exists
    rayVersion: 2.7.1
    workerGroupSpecs:
      - groupName: group
        rayStartParams: {}
        maxReplicas: 1
        minReplicas: 1
        replicas: 1
        template:
          spec:
            containers:
              - name: ray-worker
                image: 10.33.1.11:9090/datatunerx/ray271-llama2-7b-finetune-checkpoint-liantiao-test-vepk:20231213
                env:
                  - name: BASE_MODEL_DIR
                    value: '/tmp/llama2-7b/'
                  - name: CHECKPOINT_DIR
                    value: '/checkpoint/tuning/TorchTrainer_2023-12-12_22-00-28/TorchTrainer_f85ec_00000_0_2023-12-12_22-00-57/checkpoint_000000'
                lifecycle:
                  preStop:
                    exec:
                      command:
                        - /bin/sh
                        - -c
                        - ray stop
                resources:
                  limits:
                    cpu: 2000m
                    memory: 48Gi
                    nvidia.com/gpu: "1"
                  requests:
                    cpu: 1000m
                    memory: 48Gi
            nodeSelector:
              kubernetes.io/hostname: 10-33-1-11
            tolerations:
              - effect: NoSchedule
                key: nvidia.com/gpu
                operator: Exists
              - effect: NoSchedule
                key: node.kubernetes.io/disk-pressure
                operator: Exists
  serveConfig:
    deployments:
      - name: LlamaDeployment
        numReplicas: 1
        rayActorOptions:
          numGpus: 1
    importPath: inference.deployment
    runtimeEnv: |
      working_dir: file:///home/inference/inference.zip
  serveService:
    metadata:
      labels:
        app: inference
      name: finetune-sample-service
    spec:
      ports:
        - name: serve
          port: 8000
          protocol: TCP
          targetPort: 8000
      selector:
        ray.io/node-type: head
