export const TOKEN = 'ACCESS_TOKEN';
export const REFRESH_TOKEN = 'ANAKIN_REFRESH_TOKEN';
export const USERNAME = 'ANAKIN_USERNAME';
export const FAVICON = 'ANAKIN_FAVICON';
export const HAS_LOGGED = 'ANAKIN_HAS_LOGGED';
export const REGISTER_TAB = 'ANAKIN_REGISTER_TAB';
export const CHECK_FIRST_TAB = 'ANAKIN_CHECK_FIRST_TAB';
export const NAMESPACE = 'NAMESPACE';
